import configuracion_reserva_periodo_resumido
import room_reservation_summary_inherit
import quick_room_reservation_inherit
import hotel_reservation_inherit
import dreamsoft_completar_checkin
import dreamsoft_completar_checkin_relacion
